//! End-to-end pipeline integration tests.
//!
//! Each test exercises the full manifest → platform → resolver → codegen → builder → lockfile
//! chain using a mock DockerEngine (no real Docker needed).

use std::{
    cell::RefCell,
    path::{Path, PathBuf},
};

use aw_kit::{
    builder::{self, BuildResult, DockerEngine},
    codegen,
    error::Result,
    lockfile::LockFile,
    manifest::ManifestConfig,
    platform::{self, DockerRuntime, ResolvedPlatform},
    registry,
    resolver::{self, BuildPlan, BuildStep, LayerType},
};

// ---------------------------------------------------------------------------
// Mock Docker engine
// ---------------------------------------------------------------------------

struct MockEngine {
    pulled: RefCell<Vec<String>>,
    built: RefCell<Vec<String>>,
}

impl MockEngine {
    fn new() -> Self {
        Self {
            pulled: RefCell::new(Vec::new()),
            built: RefCell::new(Vec::new()),
        }
    }
}

impl DockerEngine for MockEngine {
    fn pull(&self, image: &str, _platform: &str) -> Result<String> {
        self.pulled.borrow_mut().push(image.to_string());
        Ok(format!("sha256:pull-{:x}", fxhash(image)))
    }

    fn build(
        &self,
        _dockerfile: &Path,
        _context: &Path,
        tag: &str,
        _platform: &str,
    ) -> Result<String> {
        self.built.borrow_mut().push(tag.to_string());
        Ok(format!("sha256:build-{:x}", fxhash(tag)))
    }

    fn inspect_digest(&self, image: &str) -> Result<String> {
        Ok(format!("sha256:inspect-{:x}", fxhash(image)))
    }
}

fn fxhash(s: &str) -> u64 {
    use std::hash::{DefaultHasher, Hash, Hasher};
    let mut h = DefaultHasher::new();
    s.hash(&mut h);
    h.finish()
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

fn fixture(name: &str) -> ManifestConfig {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures")
        .join(name);
    ManifestConfig::from_file(&path).unwrap()
}

fn parse_inline(toml: &str) -> ManifestConfig {
    toml::from_str(toml).unwrap()
}

/// Run the full pipeline: resolve → build (mock) → codegen → lock.
fn run_pipeline(manifest: &ManifestConfig) -> (BuildResult, ResolvedPlatform, BuildPlan, PathBuf) {
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(manifest, &platform).unwrap();
    let dir = tempfile::tempdir().unwrap();
    let project_root = dir.path().to_path_buf();

    // Create any local source dirs that fetch_sources will check.
    for pkg in &manifest.package {
        std::fs::create_dir_all(project_root.join(&pkg.path)).unwrap();
    }
    for patches in manifest.patch.values() {
        for source in patches.values() {
            if let aw_kit::manifest::PatchSource::Path { path } = source {
                std::fs::create_dir_all(project_root.join(path)).unwrap();
            }
        }
    }

    let engine = MockEngine::new();
    let result = builder::execute_plan(&engine, manifest, &plan, &platform, &project_root).unwrap();

    // Keep the dir alive by leaking it (tests are short-lived).
    std::mem::forget(dir);

    (result, platform, plan, project_root)
}

// ===========================================================================
// Scenario 1: Minimal desktop — pull only, no customization
// ===========================================================================

#[test]
fn minimal_desktop_pull_only() {
    let manifest = fixture("minimal.toml");
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // All steps should be pulls.
    assert_eq!(plan.steps.len(), 6);
    for step in &plan.steps {
        assert!(matches!(step, BuildStep::Pull { .. }));
    }

    // Platform: amd64, no CUDA, no device.
    assert_eq!(platform.arch, platform::Arch::Amd64);
    assert!(!platform.use_cuda);
    assert!(platform.device.is_none());
    assert_eq!(platform.runtime, DockerRuntime::Default);
}

#[test]
fn minimal_desktop_compose_output() {
    let manifest = fixture("minimal.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    let compose = std::fs::read_to_string(root.join(".aw-kit/compose/docker-compose.yml")).unwrap();
    assert!(compose.starts_with("# [GENERATED by aw-kit"));
    assert!(compose.contains("services:"));

    // All 6 components present.
    for name in manifest.enabled_components() {
        assert!(
            compose.contains(name),
            "missing component {name} in compose"
        );
    }

    // No nvidia runtime on desktop.
    assert!(!compose.contains("runtime: nvidia"));
    assert!(!compose.contains("devices:"));

    // network_mode and ROS env.
    assert!(compose.contains("network_mode: host"));
    assert!(compose.contains("ROS_DOMAIN_ID"));
}

#[test]
fn minimal_desktop_no_dockerfiles() {
    let manifest = fixture("minimal.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    let build_dir = root.join(".aw-kit/build");
    let dockerfiles: Vec<_> = std::fs::read_dir(&build_dir)
        .unwrap()
        .filter_map(|e| e.ok())
        .filter(|e| e.path().to_string_lossy().ends_with(".Dockerfile"))
        .collect();
    assert!(
        dockerfiles.is_empty(),
        "pull-only should produce no Dockerfiles"
    );
}

#[test]
fn minimal_desktop_lockfile() {
    let manifest = fixture("minimal.toml");
    let (result, _, _, root) = run_pipeline(&manifest);

    let lock = builder::build_lock(&manifest, &result);
    let lock_path = root.join("Autoware.lock");
    lock.write(&lock_path).unwrap();

    // Round-trip.
    let loaded = LockFile::read(&lock_path).unwrap();
    assert_eq!(loaded.workspace.autoware, "0.45.1");
    assert_eq!(loaded.components.len(), 6);
    assert!(loaded.packages.is_empty());

    // All components are unpatch.
    for comp in &loaded.components {
        assert!(!comp.patched);
        assert!(comp.patch_image.is_none());
        assert!(comp.extension_image.is_none());
        assert!(comp.digest.starts_with("sha256:"));
    }
}

// ===========================================================================
// Scenario 2: Patched components
// ===========================================================================

#[test]
fn patched_plan_has_overlays() {
    let manifest = fixture("patched.toml");
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // 4 components: localization-mapping and sensing-perception are patched.
    // pull(loc) + patch(loc) + pull(sp) + patch(sp) + pull(pc) + pull(vs) = 6 steps.
    let loc = plan.steps_for("localization-mapping");
    assert_eq!(loc.len(), 2);
    assert!(matches!(loc[0], BuildStep::Pull { .. }));
    assert!(matches!(
        loc[1],
        BuildStep::BuildOverlay {
            layer_type: LayerType::Patch,
            ..
        }
    ));

    let sp = plan.steps_for("sensing-perception");
    assert_eq!(sp.len(), 2);

    // Unpatched components are pull-only.
    assert_eq!(plan.steps_for("planning-control").len(), 1);
    assert_eq!(plan.steps_for("vehicle-system").len(), 1);
}

#[test]
fn patched_dockerfiles_content() {
    let manifest = fixture("patched.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    // localization-mapping patch Dockerfile.
    let loc_df = root.join(".aw-kit/build/localization-mapping.patch.Dockerfile");
    let content = std::fs::read_to_string(&loc_df).unwrap();
    assert!(content.starts_with("# [GENERATED by aw-kit"));
    assert!(content.contains("FROM ghcr.io/autowarefoundation/openadkit:localization-mapping"));
    assert!(content.contains("colcon build --packages-select ndt_scan_matcher"));
    assert!(content.contains("/opt/overlay_ws"));

    // sensing-perception patch Dockerfile.
    let sp_df = root.join(".aw-kit/build/sensing-perception.patch.Dockerfile");
    let content = std::fs::read_to_string(&sp_df).unwrap();
    assert!(content.contains("colcon build --packages-select lidar_centerpoint"));
}

#[test]
fn patched_compose_uses_overlay_image() {
    let manifest = fixture("patched.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    let compose = std::fs::read_to_string(root.join(".aw-kit/compose/docker-compose.yml")).unwrap();

    // Patched components should use the overlay tag, not the upstream image.
    assert!(compose.contains("localization-mapping-0.45.1-p"));
    assert!(compose.contains("sensing-perception-0.45.1-p"));

    // Unpatched components use upstream images.
    assert!(compose.contains("image: ghcr.io/autowarefoundation/openadkit:planning-control\n"));
}

#[test]
fn patched_lockfile_marks_patched() {
    let manifest = fixture("patched.toml");
    let (result, _, _, root) = run_pipeline(&manifest);

    let lock = builder::build_lock(&manifest, &result);
    lock.write(&root.join("Autoware.lock")).unwrap();

    let loc = lock
        .components
        .iter()
        .find(|c| c.name == "localization-mapping")
        .unwrap();
    assert!(loc.patched);
    assert!(loc.patch_image.is_some());
    assert!(loc.patch_digest.as_ref().unwrap().starts_with("sha256:"));

    let pc = lock
        .components
        .iter()
        .find(|c| c.name == "planning-control")
        .unwrap();
    assert!(!pc.patched);
    assert!(pc.patch_image.is_none());
}

// ===========================================================================
// Scenario 3: Custom packages (extensions)
// ===========================================================================

#[test]
fn custom_pkg_extension_overlays() {
    let manifest = fixture("custom-pkg.toml");
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // planning-control: pull + extension.
    let pc = plan.steps_for("planning-control");
    assert_eq!(pc.len(), 2);
    assert!(matches!(
        pc[1],
        BuildStep::BuildOverlay {
            layer_type: LayerType::Extension,
            ..
        }
    ));

    // sensing-perception: pull + extension.
    let sp = plan.steps_for("sensing-perception");
    assert_eq!(sp.len(), 2);

    // vehicle-system: pull only (no packages extend it).
    assert_eq!(plan.steps_for("vehicle-system").len(), 1);
}

#[test]
fn custom_pkg_dockerfiles_and_devcontainers() {
    let manifest = fixture("custom-pkg.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    // Extension Dockerfiles.
    let pc_df = root.join(".aw-kit/build/planning-control.extended.Dockerfile");
    let content = std::fs::read_to_string(&pc_df).unwrap();
    assert!(
        content.contains("COPY ./src/autosdv_behavioral_planner src/autosdv_behavioral_planner")
    );
    assert!(content.contains("colcon build --packages-select autosdv_behavioral_planner"));

    let sp_df = root.join(".aw-kit/build/sensing-perception.extended.Dockerfile");
    let content = std::fs::read_to_string(&sp_df).unwrap();
    assert!(content.contains("autosdv_v2x_bridge"));

    // Devcontainer JSON files.
    let dc = root.join(".devcontainer/autosdv_behavioral_planner.devcontainer.json");
    let content = std::fs::read_to_string(&dc).unwrap();
    assert!(content.contains("\"name\": \"autosdv_behavioral_planner\""));
    assert!(content.contains("\"--network=host\""));
    assert!(!content.contains("--runtime=nvidia")); // desktop, no nvidia

    let dc2 = root.join(".devcontainer/autosdv_v2x_bridge.devcontainer.json");
    assert!(dc2.exists());
}

#[test]
fn custom_pkg_lockfile_has_packages() {
    let manifest = fixture("custom-pkg.toml");
    let (result, _, _, _) = run_pipeline(&manifest);

    let lock = builder::build_lock(&manifest, &result);
    assert_eq!(lock.packages.len(), 2);
    assert_eq!(lock.packages[0].name, "autosdv_behavioral_planner");
    assert_eq!(lock.packages[0].extends, "planning-control");
    assert!(lock.packages[0].digest.starts_with("sha256:"));
}

// ===========================================================================
// Scenario 4: Jetson Orin (arm64, CUDA, nvidia runtime)
// ===========================================================================

#[test]
fn orin_platform_resolution() {
    let manifest = fixture("orin.toml");
    let platform = platform::resolve_platform(&manifest.platform).unwrap();

    assert_eq!(platform.arch, platform::Arch::Arm64);
    assert_eq!(platform.device.as_deref(), Some("jetson-agx-orin"));
    assert_eq!(platform.jetpack.as_deref(), Some("6.1"));
    assert_eq!(platform.cuda_arch, Some(87));
    assert!(platform.use_cuda);
    assert_eq!(platform.runtime, DockerRuntime::Nvidia);
    assert!(!platform.device_mounts.is_empty());
    assert!(platform.base_image.contains("l4t"));
}

#[test]
fn orin_cuda_variant_selection() {
    let manifest = fixture("orin.toml");
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // sensing-perception has a CUDA variant.
    let sp = plan.steps_for("sensing-perception");
    assert!(
        sp[0].output_image().ends_with("-cuda"),
        "sensing-perception should pull CUDA variant, got: {}",
        sp[0].output_image()
    );

    // planning-control has no CUDA variant.
    let pc = plan.steps_for("planning-control");
    assert!(
        !pc[0].output_image().contains("cuda"),
        "planning-control should not have CUDA variant"
    );
}

#[test]
fn orin_compose_has_nvidia_and_devices() {
    let manifest = fixture("orin.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    let compose = std::fs::read_to_string(root.join(".aw-kit/compose/docker-compose.yml")).unwrap();
    assert!(compose.contains("runtime: nvidia"));
    assert!(compose.contains("devices:"));
    assert!(compose.contains("/dev/nvhost-ctrl"));
    assert!(compose.contains("/dev/nvhost-ctrl-gpu"));
    assert!(compose.contains("/dev/nvmap"));
}

// ===========================================================================
// Scenario 5: Full manifest (Orin + patches + packages + registry)
// ===========================================================================

#[test]
fn full_manifest_pipeline() {
    let manifest = fixture("full.toml");
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // 5 components enabled: sp, lm, pc, vs, api.
    assert_eq!(manifest.enabled_components().len(), 5);

    // localization-mapping: pull + patch.
    let lm = plan.steps_for("localization-mapping");
    assert_eq!(lm.len(), 2);

    // planning-control: pull + extension (has custom package).
    let pc = plan.steps_for("planning-control");
    assert_eq!(pc.len(), 2);

    // sensing-perception: pull only (CUDA variant, no patches).
    let sp = plan.steps_for("sensing-perception");
    assert_eq!(sp.len(), 1);
    assert!(sp[0].output_image().ends_with("-cuda"));

    // api, vehicle-system: pull only.
    assert_eq!(plan.steps_for("api").len(), 1);
    assert_eq!(plan.steps_for("vehicle-system").len(), 1);
}

#[test]
fn full_manifest_codegen() {
    let manifest = fixture("full.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    // Patch Dockerfile for localization-mapping.
    let lm_df = root.join(".aw-kit/build/localization-mapping.patch.Dockerfile");
    assert!(lm_df.exists());
    let content = std::fs::read_to_string(&lm_df).unwrap();
    assert!(content.contains("ndt_scan_matcher"));

    // Extension Dockerfile for planning-control.
    let pc_df = root.join(".aw-kit/build/planning-control.extended.Dockerfile");
    assert!(pc_df.exists());
    let content = std::fs::read_to_string(&pc_df).unwrap();
    assert!(content.contains("autosdv_behavioral_planner"));

    // Compose: nvidia runtime, CUDA images, overlay images.
    let compose = std::fs::read_to_string(root.join(".aw-kit/compose/docker-compose.yml")).unwrap();
    assert!(compose.contains("runtime: nvidia"));
    assert!(compose.contains("sensing-perception-cuda")); // CUDA variant
    assert!(compose.contains("localization-mapping-0.45.1-p")); // patched
    assert!(compose.contains("planning-control-0.45.1-x")); // extended

    // Devcontainer for custom package.
    let dc = root.join(".devcontainer/autosdv_behavioral_planner.devcontainer.json");
    let content = std::fs::read_to_string(&dc).unwrap();
    assert!(content.contains("--runtime=nvidia")); // Orin platform
}

#[test]
fn full_manifest_lockfile() {
    let manifest = fixture("full.toml");
    let (result, _, _, root) = run_pipeline(&manifest);

    let lock = builder::build_lock(&manifest, &result);
    let lock_path = root.join("Autoware.lock");
    lock.write(&lock_path).unwrap();

    let loaded = LockFile::read(&lock_path).unwrap();
    assert_eq!(loaded.components.len(), 5);
    assert_eq!(loaded.packages.len(), 1);
    assert_eq!(loaded.packages[0].name, "autosdv_behavioral_planner");

    let lm = loaded
        .components
        .iter()
        .find(|c| c.name == "localization-mapping")
        .unwrap();
    assert!(lm.patched);

    let pc = loaded
        .components
        .iter()
        .find(|c| c.name == "planning-control")
        .unwrap();
    assert!(pc.extension_image.is_some());
}

#[test]
fn full_manifest_registry_tags() {
    let manifest = fixture("full.toml");
    let reg = manifest.registry.as_ref().unwrap();

    // Verify registry tag computation for different image types.
    let plain = registry::registry_tag(reg, "ghcr.io/autowarefoundation/openadkit:api");
    assert!(plain.starts_with("harbor.autosdv.edu.tw/autosdv/openadkit/"));

    let overlay = registry::registry_tag(
        reg,
        "ghcr.io/autowarefoundation/openadkit:localization-mapping-0.45.1-p12345678",
    );
    assert!(overlay.contains("localization-mapping-0.45.1-p12345678"));
}

// ===========================================================================
// Scenario 6: CUDA explicitly disabled on Jetson
// ===========================================================================

#[test]
fn orin_cuda_disabled() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch    = "arm64"
        cuda    = false
        device  = "jetson-agx-orin"
        jetpack = "6.1"

        [components]
        sensing-perception = true
        planning-control   = true
        "#,
    );

    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    assert!(!platform.use_cuda);
    assert_eq!(platform.runtime, DockerRuntime::Nvidia); // still nvidia device

    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // sensing-perception should NOT get the -cuda variant.
    let sp = plan.steps_for("sensing-perception");
    assert!(
        !sp[0].output_image().contains("cuda"),
        "CUDA disabled, should not pull -cuda variant"
    );
}

// ===========================================================================
// Scenario 7: Desktop with CUDA enabled
// ===========================================================================

#[test]
fn desktop_cuda_enabled() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch = "amd64"
        cuda = true

        [components]
        sensing-perception = true
        universe           = true
        planning-control   = true
        "#,
    );

    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    assert!(platform.use_cuda);
    assert_eq!(platform.runtime, DockerRuntime::Default); // no nvidia device

    let plan = resolver::resolve(&manifest, &platform).unwrap();

    // sensing-perception and universe have CUDA variants.
    assert!(
        plan.steps_for("sensing-perception")[0]
            .output_image()
            .ends_with("-cuda")
    );
    assert!(
        plan.steps_for("universe")[0]
            .output_image()
            .ends_with("-cuda")
    );
    // planning-control does not.
    assert!(
        !plan.steps_for("planning-control")[0]
            .output_image()
            .contains("cuda")
    );
}

// ===========================================================================
// Scenario 8: Patch + extension on same component (full stack)
// ===========================================================================

#[test]
fn patch_and_extension_same_component() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch = "amd64"

        [components]
        localization-mapping = true

        [patch.localization-mapping]
        ndt_scan_matcher = { path = "./patches/ndt" }

        [[package]]
        name    = "my_loc_ext"
        path    = "./src/my_loc_ext"
        extends = "localization-mapping"
        "#,
    );

    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    let steps = plan.steps_for("localization-mapping");
    assert_eq!(steps.len(), 3, "should have pull + patch + extension");

    // Verify chaining: each step's base_image is the previous step's output.
    if let BuildStep::BuildOverlay { base_image, .. } = steps[1] {
        assert_eq!(base_image, steps[0].output_image());
    }
    if let BuildStep::BuildOverlay { base_image, .. } = steps[2] {
        assert_eq!(base_image, steps[1].output_image());
    }

    // Codegen.
    let dir = tempfile::tempdir().unwrap();
    std::fs::create_dir_all(dir.path().join("patches/ndt")).unwrap();
    std::fs::create_dir_all(dir.path().join("src/my_loc_ext")).unwrap();
    codegen::generate_all(&manifest, &plan, &platform, dir.path()).unwrap();

    // Both Dockerfiles exist.
    assert!(
        dir.path()
            .join(".aw-kit/build/localization-mapping.patch.Dockerfile")
            .exists()
    );
    assert!(
        dir.path()
            .join(".aw-kit/build/localization-mapping.extended.Dockerfile")
            .exists()
    );
}

// ===========================================================================
// Scenario 9: Lock file verification
// ===========================================================================

#[test]
fn lockfile_verify_matching() {
    let manifest = fixture("minimal.toml");
    let (result, _, _, _root) = run_pipeline(&manifest);

    let lock = builder::build_lock(&manifest, &result);

    // Build current_digests from the result.
    let current: Vec<(String, String)> = result
        .step_results
        .iter()
        .map(|s| (s.image.clone(), s.digest.clone()))
        .collect();

    let mismatches = lock.verify(&current);
    assert!(mismatches.is_empty(), "should have no mismatches");
}

#[test]
fn lockfile_verify_detects_drift() {
    let manifest = fixture("minimal.toml");
    let (result, _, _, _) = run_pipeline(&manifest);

    let lock = builder::build_lock(&manifest, &result);

    // Tamper with one digest.
    let mut current: Vec<(String, String)> = result
        .step_results
        .iter()
        .map(|s| (s.image.clone(), s.digest.clone()))
        .collect();
    current[0].1 = "sha256:tampered".to_string();

    let mismatches = lock.verify(&current);
    assert_eq!(mismatches.len(), 1);
    assert_eq!(mismatches[0].actual, "sha256:tampered");
}

// ===========================================================================
// Scenario 10: Error cases
// ===========================================================================

#[test]
fn unknown_arch_rejected() {
    let result: std::result::Result<ManifestConfig, _> = toml::from_str(
        r#"
        [workspace]
        autoware = "0.45.1"
        [platform]
        arch = "riscv64"
        [components]
        api = true
        "#,
    );
    let manifest = result.unwrap();
    let err = platform::resolve_platform(&manifest.platform).unwrap_err();
    assert!(err.to_string().contains("unknown arch"));
}

#[test]
fn unknown_device_rejected() {
    let manifest: ManifestConfig = toml::from_str(
        r#"
        [workspace]
        autoware = "0.45.1"
        [platform]
        arch   = "arm64"
        device = "jetson-xavier"
        jetpack = "5.0"
        [components]
        api = true
        "#,
    )
    .unwrap();
    let err = platform::resolve_platform(&manifest.platform).unwrap_err();
    assert!(err.to_string().contains("unknown device"));
}

#[test]
fn jetson_missing_jetpack_rejected() {
    let manifest: ManifestConfig = toml::from_str(
        r#"
        [workspace]
        autoware = "0.45.1"
        [platform]
        arch   = "arm64"
        device = "jetson-agx-orin"
        [components]
        api = true
        "#,
    )
    .unwrap();
    let err = platform::resolve_platform(&manifest.platform).unwrap_err();
    assert!(err.to_string().contains("requires 'jetpack'"));
}

#[test]
fn arch_device_mismatch_rejected() {
    let manifest: ManifestConfig = toml::from_str(
        r#"
        [workspace]
        autoware = "0.45.1"
        [platform]
        arch    = "amd64"
        device  = "jetson-agx-orin"
        jetpack = "6.1"
        [components]
        api = true
        "#,
    )
    .unwrap();
    let err = platform::resolve_platform(&manifest.platform).unwrap_err();
    assert!(err.to_string().contains("requires arch 'arm64'"));
}

// ===========================================================================
// Scenario 11: Gitignore and directory structure
// ===========================================================================

#[test]
fn generated_directory_structure() {
    let manifest = fixture("full.toml");
    let (_, _, _, root) = run_pipeline(&manifest);

    // .aw-kit/.gitignore exists.
    let gitignore = root.join(".aw-kit/.gitignore");
    assert!(gitignore.exists());
    let content = std::fs::read_to_string(&gitignore).unwrap();
    assert!(content.contains("*"));

    // Build and compose dirs exist.
    assert!(root.join(".aw-kit/build").is_dir());
    assert!(root.join(".aw-kit/compose").is_dir());

    // Devcontainer dir exists (full.toml has packages).
    assert!(root.join(".devcontainer").is_dir());
}

// ===========================================================================
// Scenario 12: Single component
// ===========================================================================

#[test]
fn single_component_deployment() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch = "amd64"

        [components]
        api = true
        "#,
    );

    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    assert_eq!(plan.steps.len(), 1);
    assert_eq!(
        plan.steps[0].output_image(),
        "ghcr.io/autowarefoundation/openadkit:api"
    );

    let dir = tempfile::tempdir().unwrap();
    codegen::generate_all(&manifest, &plan, &platform, dir.path()).unwrap();

    let compose =
        std::fs::read_to_string(dir.path().join(".aw-kit/compose/docker-compose.yml")).unwrap();
    assert!(compose.contains("api:"));
    // Only one service.
    assert_eq!(compose.matches("image:").count(), 1);
}

// ===========================================================================
// Scenario 13: All components enabled
// ===========================================================================

#[test]
fn all_components_enabled() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch = "amd64"

        [components]
        sensing-perception   = true
        localization-mapping = true
        planning-control     = true
        vehicle-system       = true
        api                  = true
        simulator            = true
        visualizer           = true
        universe             = true
        "#,
    );

    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();

    assert_eq!(plan.steps.len(), 8);
    assert_eq!(manifest.enabled_components().len(), 8);

    let dir = tempfile::tempdir().unwrap();
    codegen::generate_all(&manifest, &plan, &platform, dir.path()).unwrap();

    let compose =
        std::fs::read_to_string(dir.path().join(".aw-kit/compose/docker-compose.yml")).unwrap();
    assert_eq!(compose.matches("image:").count(), 8);
}

// ===========================================================================
// Scenario 14: Disabled components are excluded
// ===========================================================================

#[test]
fn disabled_components_excluded() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch = "amd64"

        [components]
        planning-control   = true
        sensing-perception = false
        api                = true
        "#,
    );

    let enabled = manifest.enabled_components();
    assert_eq!(enabled.len(), 2);
    assert!(enabled.contains(&"planning-control"));
    assert!(enabled.contains(&"api"));
    assert!(!enabled.contains(&"sensing-perception"));

    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    let plan = resolver::resolve(&manifest, &platform).unwrap();
    assert_eq!(plan.steps.len(), 2);
}

// ===========================================================================
// Scenario 15: Orin Nano and Orin NX variants
// ===========================================================================

#[test]
fn orin_nano_resolves() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch    = "arm64"
        device  = "jetson-orin-nano"
        jetpack = "6.0"

        [components]
        api = true
        "#,
    );
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    assert_eq!(platform.device.as_deref(), Some("jetson-orin-nano"));
    assert!(platform.use_cuda);
    assert_eq!(platform.cuda_arch, Some(87));
}

#[test]
fn orin_nx_resolves() {
    let manifest = parse_inline(
        r#"
        [workspace]
        autoware = "0.45.1"

        [platform]
        arch    = "arm64"
        device  = "jetson-orin-nx"
        jetpack = "6.1"

        [components]
        planning-control = true
        "#,
    );
    let platform = platform::resolve_platform(&manifest.platform).unwrap();
    assert_eq!(platform.device.as_deref(), Some("jetson-orin-nx"));
    assert_eq!(platform.runtime, DockerRuntime::Nvidia);
}
