pub mod compose;
pub mod devcontainer;
pub mod dockerfile;

use std::{fs, path::Path};

use crate::{
    error::{Error, Result},
    manifest::ManifestConfig,
    platform::ResolvedPlatform,
    resolver::{BuildPlan, BuildStep},
};

const GENERATED_HEADER: &str = "# [GENERATED by aw-kit — do not edit]";
const GENERATED_HEADER_JSON: &str = "// [GENERATED by aw-kit — do not edit]";

/// Generate all build artifacts from a resolved build plan.
///
/// Creates `.aw-kit/build/` Dockerfiles for overlay steps and
/// `.aw-kit/compose/docker-compose.yml` for orchestration.
pub fn generate_all(
    manifest: &ManifestConfig,
    plan: &BuildPlan,
    platform: &ResolvedPlatform,
    project_root: &Path,
) -> Result<()> {
    let build_dir = project_root.join(".aw-kit/build");
    let compose_dir = project_root.join(".aw-kit/compose");

    ensure_dir(&build_dir)?;
    ensure_dir(&compose_dir)?;
    write_gitignore(project_root)?;

    // Generate Dockerfiles for overlay steps.
    for step in &plan.steps {
        if let BuildStep::BuildOverlay { dockerfile, .. } = step {
            let content = dockerfile::generate(step, platform);
            let path = project_root.join(dockerfile);
            write_file(&path, &content)?;
        }
    }

    // Generate docker-compose.yml.
    let compose = compose::generate(plan, platform);
    write_file(&compose_dir.join("docker-compose.yml"), &compose)?;

    // Generate devcontainer.json for each custom package.
    if !manifest.package.is_empty() {
        let devcontainer_dir = project_root.join(".devcontainer");
        ensure_dir(&devcontainer_dir)?;

        for pkg in &manifest.package {
            let final_image = plan
                .steps_for(&pkg.extends)
                .last()
                .map(|s| s.output_image())
                .unwrap_or("ros:humble-ros-base-jammy");
            let content = devcontainer::generate(pkg, final_image, platform);
            write_file(
                &devcontainer_dir.join(format!("{}.devcontainer.json", pkg.name)),
                &content,
            )?;
        }
    }

    Ok(())
}

fn ensure_dir(path: &Path) -> Result<()> {
    fs::create_dir_all(path).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn write_file(path: &Path, content: &str) -> Result<()> {
    fs::write(path, content).map_err(|source| Error::Io {
        path: path.to_path_buf(),
        source,
    })
}

fn write_gitignore(project_root: &Path) -> Result<()> {
    let gitignore_path = project_root.join(".aw-kit/.gitignore");
    if !gitignore_path.exists() {
        write_file(&gitignore_path, "# Ignore all generated content\n*\n")?;
    }
    Ok(())
}
