use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::error::{Error, Result};

/// Lock file header comment.
const LOCK_HEADER: &str = "# Autoware.lock — auto-generated by aw-kit. Commit this to git.\n\n";

/// Pinned build state for reproducible deployments.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockFile {
    pub workspace: LockWorkspace,

    #[serde(default, rename = "component")]
    pub components: Vec<LockedComponent>,

    #[serde(default, rename = "package")]
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockWorkspace {
    pub autoware: String,
    pub generated: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedComponent {
    pub name: String,
    pub image: String,
    pub digest: String,
    #[serde(default)]
    pub patched: bool,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patch_image: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub patch_digest: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension_image: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extension_digest: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub extends: String,
    pub image: String,
    pub digest: String,
}

impl LockFile {
    /// Read a lock file from disk.
    pub fn read(path: &Path) -> Result<Self> {
        let content = std::fs::read_to_string(path).map_err(|source| Error::Io {
            path: path.to_path_buf(),
            source,
        })?;
        toml::from_str(&content).map_err(|e| {
            Error::Validation(format!("failed to parse lock file {}: {e}", path.display()))
        })
    }

    /// Write the lock file to disk.
    pub fn write(&self, path: &Path) -> Result<()> {
        let serialized =
            toml::to_string_pretty(self).map_err(|e| Error::Codegen(format!("{e}")))?;
        let content = format!("{LOCK_HEADER}{serialized}");
        std::fs::write(path, content).map_err(|source| Error::Io {
            path: path.to_path_buf(),
            source,
        })
    }

    /// Verify that all locked digests match the given current digests.
    ///
    /// `current_digests` maps image references to their current digest.
    /// Returns a list of mismatches.
    pub fn verify(&self, current_digests: &[(String, String)]) -> Vec<DigestMismatch> {
        let lookup: std::collections::HashMap<&str, &str> = current_digests
            .iter()
            .map(|(img, dig)| (img.as_str(), dig.as_str()))
            .collect();

        let mut mismatches = Vec::new();

        for comp in &self.components {
            if let Some(&actual) = lookup.get(comp.image.as_str())
                && actual != comp.digest
            {
                mismatches.push(DigestMismatch {
                    image: comp.image.clone(),
                    expected: comp.digest.clone(),
                    actual: actual.to_string(),
                });
            }
            // Check patch digest if present.
            if let (Some(patch_img), Some(patch_dig)) = (&comp.patch_image, &comp.patch_digest)
                && let Some(&actual) = lookup.get(patch_img.as_str())
                && actual != patch_dig.as_str()
            {
                mismatches.push(DigestMismatch {
                    image: patch_img.clone(),
                    expected: patch_dig.clone(),
                    actual: actual.to_string(),
                });
            }
            // Check extension digest if present.
            if let (Some(ext_img), Some(ext_dig)) = (&comp.extension_image, &comp.extension_digest)
                && let Some(&actual) = lookup.get(ext_img.as_str())
                && actual != ext_dig.as_str()
            {
                mismatches.push(DigestMismatch {
                    image: ext_img.clone(),
                    expected: ext_dig.clone(),
                    actual: actual.to_string(),
                });
            }
        }

        mismatches
    }
}

#[derive(Debug, Clone)]
pub struct DigestMismatch {
    pub image: String,
    pub expected: String,
    pub actual: String,
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_lock() -> LockFile {
        LockFile {
            workspace: LockWorkspace {
                autoware: "0.45.1".to_string(),
                generated: "2026-03-13T10:00:00Z".to_string(),
            },
            components: vec![
                LockedComponent {
                    name: "planning-control".to_string(),
                    image: "ghcr.io/autowarefoundation/openadkit:planning-control".to_string(),
                    digest: "sha256:aaa".to_string(),
                    patched: false,
                    patch_image: None,
                    patch_digest: None,
                    extension_image: None,
                    extension_digest: None,
                },
                LockedComponent {
                    name: "localization-mapping".to_string(),
                    image: "ghcr.io/autowarefoundation/openadkit:localization-mapping".to_string(),
                    digest: "sha256:bbb".to_string(),
                    patched: true,
                    patch_image: Some("localization-mapping-0.45.1-p12345678".to_string()),
                    patch_digest: Some("sha256:ccc".to_string()),
                    extension_image: None,
                    extension_digest: None,
                },
            ],
            packages: vec![],
        }
    }

    #[test]
    fn round_trip_serialization() {
        let lock = sample_lock();
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("Autoware.lock");

        lock.write(&path).unwrap();
        let loaded = LockFile::read(&path).unwrap();
        assert_eq!(lock, loaded);
    }

    #[test]
    fn lock_file_has_header() {
        let lock = sample_lock();
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("Autoware.lock");

        lock.write(&path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("# Autoware.lock"));
    }

    #[test]
    fn verify_matching_digests() {
        let lock = sample_lock();
        let current = vec![
            (
                "ghcr.io/autowarefoundation/openadkit:planning-control".to_string(),
                "sha256:aaa".to_string(),
            ),
            (
                "ghcr.io/autowarefoundation/openadkit:localization-mapping".to_string(),
                "sha256:bbb".to_string(),
            ),
            (
                "localization-mapping-0.45.1-p12345678".to_string(),
                "sha256:ccc".to_string(),
            ),
        ];
        let mismatches = lock.verify(&current);
        assert!(mismatches.is_empty());
    }

    #[test]
    fn verify_detects_mismatch() {
        let lock = sample_lock();
        let current = vec![
            (
                "ghcr.io/autowarefoundation/openadkit:planning-control".to_string(),
                "sha256:CHANGED".to_string(),
            ),
            (
                "ghcr.io/autowarefoundation/openadkit:localization-mapping".to_string(),
                "sha256:bbb".to_string(),
            ),
        ];
        let mismatches = lock.verify(&current);
        assert_eq!(mismatches.len(), 1);
        assert_eq!(mismatches[0].expected, "sha256:aaa");
        assert_eq!(mismatches[0].actual, "sha256:CHANGED");
    }

    #[test]
    fn read_nonexistent_file_errors() {
        let result = LockFile::read(Path::new("/tmp/nonexistent-aw-kit-test.lock"));
        assert!(result.is_err());
    }
}
